# Use a more recent Go version that meets the requirements
FROM golang:1.24-alpine AS golang

FROM registry.access.redhat.com/ubi9/ubi:latest AS builder

ARG GOLANG_VERSION=1.24.0

# Install system dependencies
RUN dnf upgrade -y && dnf install -y \
    gcc \
    make \
    openssl-devel \
    && dnf clean all && rm -rf /var/cache/yum

# Install Go
ENV PATH=/usr/local/go/bin:$PATH

# Copy Go from the golang alpine image
COPY --from=golang /usr/local/go /usr/local/go

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY . .

# Build
RUN make build GO_BUILD_ENV='CGO_ENABLED=1 GOOS=linux'

FROM registry.access.redhat.com/ubi9/ubi:latest

WORKDIR /
USER root
COPY --from=builder /workspace/bin/manager /manager
USER 65532:65532

ENTRYPOINT ["/manager"]